name: seascape
version: 0.1.0.0
synopsis: An improved interface for UCSD CAPE data
category: Web
author: David Cao
maintainer: david@cao.st
license: MIT
license-file: LICENSE
build-type: Simple
extra-source-files:
  - CHANGELOG.md

dependencies:
  - base >= 4 && < 5

library:
  source-dirs:
    src
  dependencies:
    - aeson
    - Spock >= 0.13.0.0
    - lucid
    - Spock-lucid
    - servant
    - persistent
    - persistent-template
    - persistent-postgresql
    - monad-logger
    - text
    - wai-middleware-static

executables:
  seascape-app:
    source-dirs: app/server
    main: Main.hs
    dependencies:
      - seascape
      - Spock >= 0.13.0.0

  scrape-sparse:
    source-dirs: app/scrape-sparse
    main: Main.hs
    dependencies:
      - aeson
      - bytestring
      - cassava
      - http-client
      - http-types
      - scalpel
      - streamly
      - streamly-cassava
      - text
      - webdriver
    
